name: grocery_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  get: ^4.6.5
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^2.3.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.1
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.6.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"
  min_sdk_android: 21


flutter:

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/images/beverages_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/
    - assets/json/